[build]
  command = "npm install && npx prisma generate && npm run build"
  functions = "dist"

[functions]
  external_node_modules = ["@prisma/client", "bcryptjs"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
